"""因子候选研究引擎与命令行共用的稳定错误类型。"""

from enum import StrEnum


class FailureCode(StrEnum):
    """V0 设计定义的、可供机器读取的失败代码。"""

    RUNTIME_BOUNDARY_ERROR = "RUNTIME_BOUNDARY_ERROR"
    SPEC_SCHEMA_INVALID = "SPEC_SCHEMA_INVALID"
    DSL_TYPE_ERROR = "DSL_TYPE_ERROR"
    LOOKAHEAD_DETECTED = "LOOKAHEAD_DETECTED"
    LABEL_LEAKAGE_DETECTED = "LABEL_LEAKAGE_DETECTED"
    DATA_RELEASE_MISMATCH = "DATA_RELEASE_MISMATCH"
    STATE_COVERAGE_INCOMPLETE = "STATE_COVERAGE_INCOMPLETE"
    FIELD_MISSING = "FIELD_MISSING"
    ADJUSTMENT_CONVENTION_UNKNOWN = "ADJUSTMENT_CONVENTION_UNKNOWN"
    FACTOR_ALL_NULL = "FACTOR_ALL_NULL"
    FACTOR_COVERAGE_TOO_LOW = "FACTOR_COVERAGE_TOO_LOW"
    FACTOR_DETERMINISM_FAILED = "FACTOR_DETERMINISM_FAILED"
    STAT_FAMILY_NOT_FROZEN = "STAT_FAMILY_NOT_FROZEN"
    INSUFFICIENT_VALID_DATES = "INSUFFICIENT_VALID_DATES"
    REDUNDANCY_THRESHOLD_EXCEEDED = "REDUNDANCY_THRESHOLD_EXCEEDED"
    REFERENCE_LIBRARY_MISMATCH = "REFERENCE_LIBRARY_MISMATCH"
    ORTHOGONALIZATION_COVERAGE_LOW = "ORTHOGONALIZATION_COVERAGE_LOW"
    ORTHOGONALIZATION_RANK_DEFICIENT = "ORTHOGONALIZATION_RANK_DEFICIENT"
    ORTHOGONALIZATION_NUMERIC_UNSTABLE = "ORTHOGONALIZATION_NUMERIC_UNSTABLE"
    INCREMENTAL_INFORMATION_INSUFFICIENT = "INCREMENTAL_INFORMATION_INSUFFICIENT"
    REGIME_FEATURE_INCOMPLETE = "REGIME_FEATURE_INCOMPLETE"
    REGIME_TRAINING_HISTORY_INSUFFICIENT = "REGIME_TRAINING_HISTORY_INSUFFICIENT"
    REGIME_STANDARDIZATION_INVALID = "REGIME_STANDARDIZATION_INVALID"
    REGIME_FIT_NOT_CONVERGED = "REGIME_FIT_NOT_CONVERGED"
    REGIME_COVARIANCE_INVALID = "REGIME_COVARIANCE_INVALID"
    REGIME_TRANSITION_INVALID = "REGIME_TRANSITION_INVALID"
    REGIME_STATE_OCCUPANCY_TOO_LOW = "REGIME_STATE_OCCUPANCY_TOO_LOW"
    REGIME_CORE_DURATION_TOO_SHORT = "REGIME_CORE_DURATION_TOO_SHORT"
    REGIME_STATES_REDUNDANT = "REGIME_STATES_REDUNDANT"
    REGIME_FILTER_INVALID = "REGIME_FILTER_INVALID"
    REGIME_MAPPING_INVALID = "REGIME_MAPPING_INVALID"
    REGIME_ALL_CANDIDATES_UNAVAILABLE = "REGIME_ALL_CANDIDATES_UNAVAILABLE"
    REGIME_DOWNSTREAM_MANIFEST_MISMATCH = "REGIME_DOWNSTREAM_MANIFEST_MISMATCH"
    COVERAGE_INPUT_MISMATCH = "COVERAGE_INPUT_MISMATCH"
    COVERAGE_PAIR_INVALID = "COVERAGE_PAIR_INVALID"
    LLM_PRIVACY_VIOLATION = "LLM_PRIVACY_VIOLATION"
    LLM_POLICY_NOT_AUTHORIZED = "LLM_POLICY_NOT_AUTHORIZED"
    LLM_EXPORT_NOT_AUTHORIZED = "LLM_EXPORT_NOT_AUTHORIZED"
    LLM_PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
    LLM_RESPONSE_INVALID = "LLM_RESPONSE_INVALID"
    LLM_STATE_TRANSITION_INVALID = "LLM_STATE_TRANSITION_INVALID"
    LLM_FAMILY_NOT_SEALED = "LLM_FAMILY_NOT_SEALED"
    LLM_DATA_IDENTITY_OVERLAP = "LLM_DATA_IDENTITY_OVERLAP"
    PORTFOLIO_POLICY_INVALID = "PORTFOLIO_POLICY_INVALID"
    PORTFOLIO_DATA_CONTRACT_INVALID = "PORTFOLIO_DATA_CONTRACT_INVALID"
    CALENDAR_CONTRACT_INVALID = "CALENDAR_CONTRACT_INVALID"
    BARRA_POLICY_INVALID = "BARRA_POLICY_INVALID"
    BARRA_DATA_CONTRACT_INVALID = "BARRA_DATA_CONTRACT_INVALID"
    PILOT_INPUT_CONTRACT_INVALID = "PILOT_INPUT_CONTRACT_INVALID"
    BENCHMARK_SOURCE_UNAVAILABLE = "BENCHMARK_SOURCE_UNAVAILABLE"
    LEDGER_CONCURRENT_WRITER = "LEDGER_CONCURRENT_WRITER"
    LEDGER_CORRUPT = "LEDGER_CORRUPT"
    AUDIT_QUARANTINED = "AUDIT_QUARANTINED"
    EVOLUTION_CONTEXT_INVALID = "EVOLUTION_CONTEXT_INVALID"
    COVERAGE_GAP_INVALID = "COVERAGE_GAP_INVALID"
    APPROVAL_COUNT_INVALID = "APPROVAL_COUNT_INVALID"
    DESIGN_DIVERSITY_FAILED = "DESIGN_DIVERSITY_FAILED"
    MEMORY_IMMUTABILITY_VIOLATION = "MEMORY_IMMUTABILITY_VIOLATION"
    POLLUTED_FAMILY_REJECTED = "POLLUTED_FAMILY_REJECTED"
    EVOLUTION_HASH_MISMATCH = "EVOLUTION_HASH_MISMATCH"


class FactorMinerError(Exception):
    """携带稳定机器可读代码的领域错误。"""

    def __init__(self, code: FailureCode, message: str) -> None:
        """初始化领域错误。

        参数：
            code: 稳定的失败代码。
            message: 面向开发者的具体失败说明。

        返回：
            无。初始化异常对象的代码、消息和可读字符串。
        """
        self.code = code
        self.message = message
        super().__init__(f"{code}: {message}")
